name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
         mpi: ${{ matrix.mpi }}
    - name: PDR test
      run: cd Test_Problems/HD/Chemistry/PDR/
    - name: make
      run: make
    - name: run
      run: mpirun -np 2 ./pluto
