name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
         mpi: ${{ matrix.mpi }}
    - name: make
      run: |
        cd Test_Problems/HD/Chemistry/PDR/
        make
    - name: run
      run: |
        cd Test_Problems/HD/Chemistry/PDR/
        mpirun -np 2 ./pluto
